### PR TITLE
Added V icon for Safari toolbar

### PR DESCRIPTION
**Pull request by ChrisLTD**
Added a new V icon for the toolbar based on the V from my Vimari Extension icon a few years back.

image

I'm working on a PR to add the icon to the Extensions preference menu in Safari.

### CODE REVIEW

**Comment by nchase** [comment]
Please excuse my ignorance: are Safari Extension icons always PDFs?

**Comment by ChrisLTD** [comment]
@nchase,
I think they can be PNGs, but PDFs should rescale nicely for retina and non-retina screens alike.

**Comment by nchase** [comment]
Cool! The file size is pretty small too. I hope this gets into master soon!

**Comment by danielcompton** [comment]
Thanks!

I've made a V icon based off of the Mac App icon, which itself is derived from the Vim logo, but I'm not very happy with it. I plan to revisit the logo sometime, and might like a thinner V logo like you have here.

**Comment by danielcompton** [comment]
Will close this for now, but may revisit later.

**Pull request closed without merging**
