### PR TITLE
Ports closeTab and tab navigation for Safari 12 (macOS 10.14.4+ only)

### PR DESCRIPTION
**Pull request by isundaylee**
Currently with Vimari 2.0 (for Safari 12), tab closing and tab navigation (i.e. move to the left/right tab don't seem to work. These commits port them to use the new native extension API. However, `[SFSafariTab close...]` and `[SFSafariWindow getAllTabs...]` are only available on macOS 10.14.4+. Sadly I haven't yet found a way to make those functionalities work for earlier versions of macOS.

### CODE REVIEW

**Comment by isundaylee** [comment]
I noticed that there are some conflicts with master in this PR as well as #133. I can go ahead and rebase but I just wanna make sure that there is interest in eventually merging these PRs before doing that. Definitely not trying to rush things but just wanna make sure that these PRs have not fallen through the crack.

**Comment by danielcompton** [comment]
Thanks, for this! I only discovered it after I had done most of the same work. Is there anything left in here that hasn't been implemented already?

**Comment by isundaylee** [comment]
@danielcompton Oh ok I haven't pulled master in a while so I didn't notice that they've already been implemented. Feel free to close this!

**Comment by isundaylee** [comment]
BTW is #133 also implemented? If not I can rebase that one some time.

**Comment by nbelzer** [comment]
As this feature is already available I'm closing this PR.

**Pull request closed without merging**
