### PR TITLE
Added smooth-scrolling

### PR DESCRIPTION
**Pull request by jacobchrismarsh**
Added smooth scrolling to extension. Users can change the 'scrollType' in settings.js to either "smooth", "instant", or "auto"

### CODE REVIEW

**Comment by jacobchrismarsh** [comment]
I'm confused because [this](https://developer.mozilla.org/en-US/docs/Web/API/ScrollToOptions) says that Safari doesn't support ScrollToOptions, but in the [Safari Technology Preview Release 13](https://webkit.org/blog/6937/release-notes-for-safari-technology-preview-release-13/), which came out 2+ years ago, it says that they added support for ScrollToOptions. I would assume that they've since migrated those features over into the main Safari app.

**Comment by simeg** [comment]
That is confusing, I agree. Now when I test I can't make it scroll smoothly..

Also looking at [Apple's docs](https://developer.apple.com/documentation/webkitjs/domwindow/1632960-scrollby) the `scrollBy` function doesn't even support options. Did you ever make it work in Safari? 🙂

**Comment by anongit** [comment]
I used the [smoothscroll](https://github.com/iamdustan/smoothscroll/) polyfill with the code like this:
```js
window.scrollBy({ top: window.innerHeight / 2, behavior: 'smooth' });
```
I also reduced `SCROLL_TIME` in the polyfill to closer match the native page scroll.
Works okay.

**Comment by kcmannem** [comment]
@jacobchrismarsh are you planning on continuing this? I would love to see it be added!

**Comment by jacobchrismarsh** [comment]
@kcmannem I stopped working on it because Apple's documentation was confusing on whether or not Safari supported smooth scrolling. That being said, @anongit 's [comment](https://github.com/televator-apps/vimari/pull/115#issuecomment-496609325) seems to suggest that it might be possible. I have plenty of time over the holidays, so I'll give it another look over.

**Comment by de-Blaxe** [comment]
It is possible according to the implementation in sVim. I put the same implementation in Vimari and it worked.

**Comment by kcmannem** [comment]
@de-Blaxe are you willing to make a PR for this? I can do so if not.

**Comment by jacobchrismarsh** [comment]
Whoa @de-Blaxe [this code](https://github.com/flippidippi/sVim/blob/525d7a31be2f9dfadedfa6b66c011488432e97fb/sVim.safariextension/sVimHelper.js#L37-L77) is super interesting. I never would have considered this!

**Comment by kcmannem** [comment]
@jacobchrismarsh are you picking this back up again?

**Comment by de-Blaxe** [comment]
@kcmannem You can go ahead and make a PR for it.

**Comment by danielcompton** [comment]
I can see [code](https://github.com/WebKit/webkit/commit/6b0ee98f241d4912bd4e7ffcacb0cf19df8ece72) relating to this in WebKit, but code like `window.scrollBy({left: 0, top: 300, behavior: 'smooth'});` that smooth scrolls in Firefox and Chrome doesn't work in Safari :(

**Comment by abnerf** [comment]
@jacobchrismarsh hey, curious to know what happened to this PR after all. Thanks!

**Comment by jacobchrismarsh** [comment]
@abnerf definitely abandoned as far as I'm concerned. @nbelzer implemented smooth scrolling in #182, and it works great! It honestly allowed me to switch over from Chrome and Vimium to Safari and Vimari.

**Pull request closed without merging**
